[package]
name = "lemmy_apub_lib_derive"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
quote = "1.0"